"""
du_lieu_roadmap.py — Nội dung Roadmap & Checklist ChatMQL.

Tách khỏi phần dựng bảng vì đây là thứ đội nghiệp vụ sửa nhiều nhất: đổi trạng
thái, thêm hạng mục, ghi chú lý do. Sửa ở đây rồi chạy cap-nhat-roadmap-sheet.py
là file trên Drive cập nhật theo.
"""

TRANG_THAI = ["Xong", "Đang làm", "Chờ phụ thuộc", "Chưa bắt đầu", "Tạm dừng"]
UU_TIEN = ["Cao", "Trung bình", "Thấp"]

# (Giai đoạn, Module, Hạng mục, Kết quả cần đạt, Trạng thái, Ưu tiên,
#  Phụ trách, Bắt đầu, Hoàn thành, Ghi chú)
ROADMAP = [
    ('GĐ1 · Nền tảng', 'Hội thoại', 'Viết lại giao diện trên nền eCDP', 'Toàn bộ màn hội thoại chạy trên mã nguồn mới', 'Xong', 'Cao', '', '', '', 'Fork mã nguồn eCDP, cắm vào backend TDVN'),
    ('GĐ1 · Nền tảng', 'Hội thoại', 'Gộp đa kênh về một hộp thư', 'Zalo cá nhân, Zalo OA, Web chat, Facebook, TikTok Shop', 'Xong', 'Cao', '', '', '', ''),
    ('GĐ1 · Nền tảng', 'Cài đặt', 'Phân quyền động theo vai trò', 'Menu và API lọc theo quyền thật', 'Xong', 'Cao', '', '', '', 'Server vẫn chặn 403 độc lập với giao diện'),
    ('GĐ1 · Nền tảng', 'Toàn hệ thống', 'Bỏ 4 module không dùng', 'Báo giá, Ưu đãi, Chiến dịch ZNS, Phân tích', 'Xong', 'Trung bình', '', '', '', ''),
    ('GĐ2 · Bán hàng trong hội thoại', 'Tài liệu bán hàng', 'Thư viện thư mục nhiều cấp', 'Admin tự dựng cây thư mục, 7 loại tài nguyên', 'Xong', 'Cao', '', '', '', ''),
    ('GĐ2 · Bán hàng trong hội thoại', 'Tài liệu bán hàng', 'Luồng gửi khách hai bước', 'Chọn nguồn, tick từng phần, xem trước rồi gửi', 'Xong', 'Cao', '', '', '', 'Thay luồng cũ tick rồi bắn'),
    ('GĐ2 · Bán hàng trong hội thoại', 'Đơn hàng', 'Tạo đơn ngay trong hội thoại', 'Đơn đẩy thẳng sang CRM', 'Xong', 'Cao', '', '', '', ''),
    ('GĐ2 · Bán hàng trong hội thoại', 'Đơn hàng', 'Tin xác nhận theo mẫu phiếu bán hàng', 'Đủ thông tin công ty, bảng hàng, tiền, hoá đơn GTGT', 'Xong', 'Cao', '', '', '', ''),
    ('GĐ2 · Bán hàng trong hội thoại', 'Đơn hàng', 'Mã khách hàng trên phiếu', 'Phiếu in được mã KH như bản giấy', 'Chờ phụ thuộc', 'Trung bình', '', '', '', 'CRM chưa trả mã khách khi tạo đơn — cần CRM sửa'),
    ('GĐ3 · Sản phẩm & Mini App', 'Sản phẩm', 'Cấu trúc dữ liệu sản phẩm chuẩn', 'Một hợp đồng dữ liệu cho cả giao diện và AI', 'Xong', 'Cao', '', '', '', 'Đổi nguồn chỉ cần map lại normalizeProduct'),
    ('GĐ3 · Sản phẩm & Mini App', 'Sản phẩm', 'Nguồn tạm từ bảng nội bộ', '78 sản phẩm thật hiển thị được ngay', 'Xong', 'Cao', '', '', '', 'Bảng nội bộ sẽ bỏ khi có API chính thức'),
    ('GĐ3 · Sản phẩm & Mini App', 'Sản phẩm', 'Đấu nối API sản phẩm chính thức TDVN', 'Giá và tồn kho lấy từ hệ thống gốc', 'Xong', 'Cao', '', '', '', 'Đã chạy trên apifm.traduoc.vn — 84 sản phẩm, 22 danh mục, tìm kiếm và phân trang phía máy chủ'),
    ('GĐ3 · Sản phẩm & Mini App', 'Sản phẩm', 'Ghép mã Mini App cho sản phẩm', 'Đủ mã để dựng link gửi khách', 'Đang làm', 'Cao', '', '', '', 'Đã ghép 11/45 sản phẩm Mini App; còn lại tên hai bên khác nhau, cần người xác nhận'),
    ('GĐ3 · Sản phẩm & Mini App', 'Sản phẩm', 'Tab Sản phẩm trong hội thoại', 'Thẻ hàng ngang có ảnh, giá, nút gửi', 'Xong', 'Cao', '', '', '', ''),
    ('GĐ3 · Sản phẩm & Mini App', 'Sản phẩm', 'Link Mini App thật', 'Khách bấm vào xem và đặt được hàng', 'Xong', 'Cao', '', '', '', 'Đã lấy mẫu link từ hệ quản trị Mini App, sinh ra trùng khớp tuyệt đối'),
    ('GĐ4 · AI', 'AI', 'Trợ lý nội bộ cho nhân viên', 'Nhân viên tra cứu sản phẩm, chính sách, quy trình', 'Xong', 'Cao', '', '', '', ''),
    ('GĐ4 · AI', 'AI', 'AI đọc tài liệu bán hàng khi tư vấn', 'Câu trả lời bám tài liệu công ty', 'Xong', 'Cao', '', '', '', 'Thêm lớp ngữ cảnh có ngân sách ký tự riêng'),
    ('GĐ4 · AI', 'AI', 'Nhập tài liệu thật cho AI đọc', 'Đủ tư liệu để AI tư vấn đúng', 'Chưa bắt đầu', 'Cao', '', '', '', 'Nhân sự nhập nội dung, hệ thống đã sẵn sàng'),
    ('GĐ4 · AI', 'AI', 'Đánh giá chất lượng câu trả lời', 'Có số liệu để biết AI trả lời tốt tới đâu', 'Chưa bắt đầu', 'Trung bình', '', '', '', ''),
    ('GĐ5 · Đào tạo & vận hành', 'Hướng dẫn sử dụng', 'Nút HDSD và hướng dẫn theo module', 'Nhân viên mới tự học được', 'Xong', 'Trung bình', '', '', '', '9 module có phần đọc'),
    ('GĐ5 · Đào tạo & vận hành', 'Hướng dẫn sử dụng', 'Tour tương tác module Hội thoại', '23 bước, 6 chương, đi từ tổng quan xuống từng nút', 'Xong', 'Trung bình', '', '', '', ''),
    ('GĐ5 · Đào tạo & vận hành', 'Hướng dẫn sử dụng', 'Tour chi tiết các module còn lại', 'Mỗi module chính có tour đầy đủ', 'Chưa bắt đầu', 'Trung bình', '', '', '', 'Tạo đơn, Sản phẩm, Tài liệu bán hàng, AI'),
    ('GĐ5 · Đào tạo & vận hành', 'Toàn hệ thống', 'Đào tạo đội sale', 'Cả đội dùng được không cần hỏi lại', 'Chưa bắt đầu', 'Cao', '', '', '', ''),
    ('GĐ6 · Bảo mật & bàn giao', 'Toàn hệ thống', 'Gỡ bí mật khỏi kho mã công khai', 'Không còn khoá dịch vụ nào trong lịch sử git', 'Chưa bắt đầu', 'Cao', '', '', '', 'Xem sheet Việc tồn & rủi ro'),
    ('GĐ6 · Bảo mật & bàn giao', 'Tích hợp', 'Bật xác thực cho cầu nối CRM', 'Cầu nối từ chối yêu cầu không có khoá hợp lệ', 'Chưa bắt đầu', 'Cao', '', '', '', 'Hiện kiểm tra bị vô hiệu, cầu nối coi như mở'),
    ('GĐ6 · Bảo mật & bàn giao', 'Toàn hệ thống', 'Gộp PR #1 vào main', 'Mã nguồn mới thành bản chính', 'Đang làm', 'Cao', '', '', '', 'Chờ anh thangvm review'),
    ('GĐ6 · Bảo mật & bàn giao', 'Toàn hệ thống', 'Đưa lên môi trường thật', 'Đội sale dùng bản chính thức', 'Chưa bắt đầu', 'Cao', '', '', '', ''),
]

# (Module, Nhóm chức năng, Hạng mục, Trạng thái, Phụ trách, Ghi chú)
CHECKLIST = [
    ('Hội thoại', 'Hộp thư', 'Gộp đa kênh về một danh sách', 'Xong', '', ''),
    ('Hội thoại', 'Hộp thư', 'Bộ lọc Tất cả · Chưa đọc · Chưa trả lời', 'Xong', '', ''),
    ('Hội thoại', 'Hộp thư', 'Bộ lọc AI tư vấn', 'Xong', '', 'Lọc hội thoại đang để AI tự trả lời'),
    ('Hội thoại', 'Hộp thư', 'Tìm theo tên và số điện thoại', 'Xong', '', ''),
    ('Hội thoại', 'Khung chat', 'Gửi chữ, ảnh, tệp, sticker', 'Xong', '', ''),
    ('Hội thoại', 'Khung chat', 'Lọc tin theo người gửi', 'Xong', '', 'Tất cả · Khách · AI · Nhân viên'),
    ('Hội thoại', 'Khung chat', 'Thư viện ảnh, tệp, liên kết của hội thoại', 'Xong', '', ''),
    ('Hội thoại', 'Khung chat', 'Kéo lịch sử cũ từ Zalo', 'Xong', '', ''),
    ('Hội thoại', 'Khung chat', 'Trả lời trích dẫn và nhắc tên trong nhóm', 'Xong', '', ''),
    ('Hội thoại', 'Cột hồ sơ khách', 'Hồ sơ CRM theo số điện thoại', 'Xong', '', ''),
    ('Hội thoại', 'Cột hồ sơ khách', 'Thẻ hạng hội viên cạnh tiêu đề', 'Xong', '', ''),
    ('Hội thoại', 'Cột hồ sơ khách', 'Ghi chú nhanh theo hội thoại', 'Xong', '', ''),
    ('Hội thoại', 'Cột hồ sơ khách', 'Phân tích khách hàng bằng AI', 'Xong', '', ''),
    ('Đơn hàng', 'Tạo đơn', 'Điền sẵn thông tin khách từ hồ sơ', 'Xong', '', ''),
    ('Đơn hàng', 'Tạo đơn', 'Ô tìm sản phẩm và ô tìm quà tặng tách riêng', 'Xong', '', 'Đồng nhất với CRM'),
    ('Đơn hàng', 'Tạo đơn', 'Chọn kho và loại đơn', 'Xong', '', ''),
    ('Đơn hàng', 'Tạo đơn', 'Phí vận chuyển tính theo quy tắc CRM', 'Xong', '', ''),
    ('Đơn hàng', 'Thanh toán', 'COD và chuyển khoản VietQR', 'Xong', '', ''),
    ('Đơn hàng', 'Thanh toán', 'Ghi nhận tiền cọc, tính phần còn thu', 'Xong', '', ''),
    ('Đơn hàng', 'Sau khi tạo', 'Phiếu bán hàng gửi khách qua Zalo', 'Xong', '', ''),
    ('Đơn hàng', 'Sau khi tạo', 'Thông tin công ty đọc từ cấu hình', 'Xong', '', 'Đổi được mà không phải sửa mã'),
    ('Đơn hàng', 'Sau khi tạo', 'In mã khách hàng lên phiếu', 'Chờ phụ thuộc', '', 'CRM chưa trả mã khách khi tạo đơn'),
    ('Sản phẩm', 'Nguồn dữ liệu', 'Cấu trúc dữ liệu chuẩn CrmProduct', 'Xong', '', ''),
    ('Sản phẩm', 'Nguồn dữ liệu', 'Nguồn cầu nối CRM bằng khoá dịch vụ', 'Xong', '', ''),
    ('Sản phẩm', 'Nguồn dữ liệu', 'Nguồn API dashboard bằng token', 'Xong', '', 'Token hết hạn theo phiên, chỉ hợp thử nghiệm'),
    ('Sản phẩm', 'Nguồn dữ liệu', 'Nguồn bảng nội bộ dùng tạm', 'Xong', '', '78 sản phẩm thật, sẽ bỏ khi có API chính thức'),
    ('Sản phẩm', 'Nguồn dữ liệu', 'Nguồn chính thức FM backend', 'Xong', '', 'Đang dùng thật; đổi nguồn ngay trong giao diện, không cần khởi động lại'),
    ('Sản phẩm', 'Danh sách', 'Trang duyệt sản phẩm có lọc và phân trang', 'Xong', '', ''),
    ('Sản phẩm', 'Danh sách', 'Ảnh đại diện trên thẻ sản phẩm', 'Xong', '', ''),
    ('Sản phẩm', 'Gửi khách', 'Tab Sản phẩm trong hội thoại', 'Xong', '', ''),
    ('Sản phẩm', 'Gửi khách', 'Gửi thẻ sản phẩm kèm link Mini App', 'Đang làm', '', 'Link chạy đúng; còn 34 sản phẩm Mini App chưa ghép được với dữ liệu ChatMQL'),
    ('Sản phẩm', 'Gửi khách', 'Ẩn hàng ngừng bán khỏi danh sách gửi', 'Xong', '', ''),
    ('Tài liệu bán hàng', 'Cấu trúc', 'Cây thư mục nhiều cấp, sắp xếp được', 'Xong', '', ''),
    ('Tài liệu bán hàng', 'Cấu trúc', 'Bảy loại tài nguyên, mỗi loại một form', 'Xong', '', 'Sản phẩm, ảnh, video, PDF, tài liệu, văn bản, liên kết'),
    ('Tài liệu bán hàng', 'Cấu trúc', 'Ba mức hiển thị, chặn ở máy chủ', 'Xong', '', 'Gửi khách · Nội bộ · Chỉ AI đọc'),
    ('Tài liệu bán hàng', 'Cấu trúc', 'Ghép tài liệu với sản phẩm bằng mã', 'Xong', '', ''),
    ('Tài liệu bán hàng', 'Gửi khách', 'Bước 1 chọn sản phẩm hoặc tài liệu chung', 'Xong', '', ''),
    ('Tài liệu bán hàng', 'Gửi khách', 'Bước 2 tick từng phần muốn gửi', 'Xong', '', 'Giới thiệu kèm giá · từng tấm ảnh · video'),
    ('Tài liệu bán hàng', 'Gửi khách', 'Xem trước đúng các tin khách sẽ nhận', 'Xong', '', ''),
    ('Tài liệu bán hàng', 'Gửi khách', 'Lời nhắn mở đầu trước gói tài liệu', 'Xong', '', ''),
    ('Tài liệu bán hàng', 'Nội dung', 'Nhập tài liệu thật cho từng danh mục', 'Chưa bắt đầu', '', 'Nhân sự nhập, hệ thống đã sẵn sàng'),
    ('Tài liệu bán hàng', 'Nội dung', 'Nhập tư liệu từ Google Drive của công ty', 'Chưa bắt đầu', '', 'Cần chốt cách ánh xạ thư mục sang mã sản phẩm'),
    ('AI', 'Trả lời khách', 'Ba chế độ Tự động · Gợi ý · Tắt', 'Xong', '', ''),
    ('AI', 'Trả lời khách', 'Tạm dừng AI theo mốc phút', 'Xong', '', ''),
    ('AI', 'Trả lời khách', 'Nhóm: chỉ trả lời khi được nhắc tên', 'Xong', '', 'Cài đặt AI đặt chung; menu Chế độ AI ở từng nhóm ghi đè được và thắng cài đặt chung'),
    ('AI', 'Trả lời khách', 'Đội bot, mỗi bot có tính cách và kịch bản', 'Xong', '', ''),
    ('AI', 'Ngữ cảnh', 'Đọc kiến thức chung và hồ sơ khách', 'Xong', '', ''),
    ('AI', 'Ngữ cảnh', 'Đọc tài liệu bán hàng khi tư vấn', 'Xong', '', ''),
    ('AI', 'Ngữ cảnh', 'Đọc ghi chú nội bộ của nhân viên', 'Xong', '', ''),
    ('AI', 'Ngữ cảnh', 'Không để lộ tài liệu nội bộ ra khách', 'Xong', '', 'Đã kiểm chứng'),
    ('AI', 'Trợ lý nội bộ', 'Khung chat riêng cho nhân viên tra cứu', 'Xong', '', ''),
    ('AI', 'Trợ lý nội bộ', 'Chọn bot để hỏi', 'Xong', '', ''),
    ('AI', 'Chất lượng', 'Đo chất lượng câu trả lời', 'Chưa bắt đầu', '', ''),
    ('Khách hàng', 'Danh sách', 'Tra cứu theo tên và số điện thoại', 'Xong', '', ''),
    ('Khách hàng', 'Hồ sơ', 'Lịch sử mua hàng và điểm tích luỹ', 'Xong', '', ''),
    ('Khách hàng', 'Hồ sơ', 'Hạng hội viên tính theo chi tiêu', 'Xong', '', ''),
    ('CDP', 'Hợp nhất', 'Gom hồ sơ nhiều kênh về một khách', 'Xong', '', ''),
    ('CDP', 'Phân nhóm', 'Chia nhóm theo hành vi mua', 'Chưa bắt đầu', '', ''),
    ('Tự động hoá', 'Quy tắc', 'Kích hoạt theo sự kiện hội thoại', 'Xong', '', ''),
    ('Tự động hoá', 'Quy tắc', 'Kiểm thử quy tắc trước khi bật rộng', 'Chưa bắt đầu', '', 'Quy tắc sai nhân bản lỗi rất nhanh'),
    ('Hướng dẫn sử dụng', 'Phần đọc', 'Chín module có nội dung hướng dẫn', 'Xong', '', ''),
    ('Hướng dẫn sử dụng', 'Tour', 'Khung tour tương tác tô sáng giao diện thật', 'Xong', '', ''),
    ('Hướng dẫn sử dụng', 'Tour', 'Tour Hội thoại đầy đủ 23 bước', 'Xong', '', ''),
    ('Hướng dẫn sử dụng', 'Tour', 'Tour Tạo đơn chi tiết', 'Chưa bắt đầu', '', ''),
    ('Hướng dẫn sử dụng', 'Tour', 'Tour Sản phẩm chi tiết', 'Chưa bắt đầu', '', 'Hiện mới có bản rút gọn 3 bước'),
    ('Hướng dẫn sử dụng', 'Tour', 'Tour Tài liệu bán hàng chi tiết', 'Chưa bắt đầu', '', 'Hiện mới có bản rút gọn 2 bước'),
    ('Hướng dẫn sử dụng', 'Tour', 'Tour AI chi tiết', 'Chưa bắt đầu', '', ''),
    ('Vận hành', 'Kênh', 'Zalo cá nhân', 'Xong', '', ''),
    ('Vận hành', 'Kênh', 'Zalo OA', 'Xong', '', ''),
    ('Vận hành', 'Kênh', 'Web chat trên website', 'Xong', '', ''),
    ('Vận hành', 'Kênh', 'Facebook và TikTok Shop', 'Xong', '', ''),
    ('Vận hành', 'Triển khai', 'Gộp PR #1 vào main', 'Đang làm', '', 'Chờ review'),
    ('Vận hành', 'Triển khai', 'Đưa lên môi trường thật', 'Chưa bắt đầu', '', ''),
    ('Vận hành', 'Triển khai', 'Đào tạo đội sale', 'Chưa bắt đầu', '', ''),
]

# (Loại, Vấn đề, Ảnh hưởng, Cần làm gì, Mức độ, Trạng thái, Ghi chú)
TON_DONG = [
    ('Dữ liệu', '51 trong 84 sản phẩm chưa có trên Mini App', 'Nút gửi link bị khoá ở những sản phẩm đó', 'Đăng thêm sản phẩm lên Mini App, hoặc chấp nhận chỉ gửi link cho 33 sản phẩm đang có', 'Trung bình', 'Chờ phụ thuộc', 'Đã tự ghép 33 sản phẩm theo quy tắc mã FM cộng hậu tố -ZL'),
    ('Chặn tính năng', 'Chưa có địa chỉ Mini App thật', 'Không gửi được link đặt hàng cho khách', 'Đã xong: lấy từ hệ quản trị Mini App, đã đặt vào cấu hình', 'Cao', 'Xong', 'Mini App id 1575573710529516487'),
    ('Dữ liệu', 'Sản phẩm FM hầu hết chưa có ảnh', 'Thẻ sản phẩm gửi khách hiện ô trống', 'Bổ sung ảnh ở hệ thống FM, hoặc lấy ảnh từ tài liệu bán hàng', 'Trung bình', 'Chưa bắt đầu', 'Chỉ 5/84 sản phẩm có ảnh'),
    ('Chặn tính năng', 'CRM không trả mã khách khi tạo đơn', 'Phiếu bán hàng thiếu mã khách so với bản giấy', 'Bên CRM bổ sung trường này vào phản hồi', 'Trung bình', 'Chờ phụ thuộc', ''),
    ('Dữ liệu', '29 sản phẩm đang ở trạng thái ngừng bán', 'Không hiện ở màn gửi khách, gồm cả mặt hàng chủ lực', 'Xác nhận mặt hàng nào còn bán để mở lại', 'Trung bình', 'Chờ phụ thuộc', 'Vạn Phúc, Vạn Thọ, Vạn Thịnh…'),
    ('Dữ liệu', 'Tài liệu bán hàng thật chưa được nhập', 'AI và sale thiếu tư liệu để tư vấn', 'Phân công nhân sự nhập nội dung theo từng danh mục', 'Cao', 'Chưa bắt đầu', ''),
    ('Bảo mật', 'Kho mã công khai có chứa khoá dịch vụ đã commit', 'Ai cũng tải về dùng được các khoá đó', 'Đổi toàn bộ khoá bị lộ và gỡ khỏi lịch sử git', 'Cao', 'Chưa bắt đầu', 'Tệp khoá Google, bản sao lưu cơ sở dữ liệu'),
    ('Bảo mật', 'Cầu nối CRM không thực sự kiểm tra khoá', 'Bất kỳ ai gọi được cũng đọc ghi được dữ liệu CRM', 'Bật lại phần kiểm tra ở cầu nối phía CRM', 'Cao', 'Chưa bắt đầu', ''),
    ('Bảo mật', 'Khoá và mật khẩu ghi cứng trong mã nguồn', 'Lộ khi mã nguồn bị đọc', 'Chuyển hết sang biến môi trường', 'Cao', 'Chưa bắt đầu', ''),
    ('Bảo mật', 'Token CRM từng dán qua chat có chứa mật khẩu dạng thô', 'Tài khoản bị chiếm nếu token lọt ra ngoài', 'Đổi mật khẩu tài khoản CRM liên quan', 'Cao', 'Chưa bắt đầu', ''),
    ('Riêng tư', 'Thư mục uploads trong git có ảnh chat của khách thật', 'Lộ thông tin khách qua kho mã công khai', 'Gỡ khỏi git và chuyển sang lưu ngoài', 'Cao', 'Chưa bắt đầu', ''),
    ('Cần làm rõ', 'Chưa rõ khoá Evotech dùng cho đầu nối nào', 'Không đấu nối được dịch vụ liên quan', 'Cho biết endpoint và cách gửi khoá', 'Thấp', 'Chờ phụ thuộc', ''),
    ('Vận hành', 'Backend nội bộ đang giữ phiên Zalo thật của doanh nghiệp', 'Thử nghiệm nhầm sẽ gửi tin cho khách thật', 'Chỉ thử trên hội thoại Web Chat, kiểm tra mã hội thoại trước khi gửi', 'Cao', 'Đang làm', 'Đã xảy ra một lần'),
]
